#pragma once
#include "../config.h"
#define _PATH_PHANTASIA_STATE	_PATH_GAME_STATE "phantasia/"
#define	_PATH_GOLD	_PATH_PHANTASIA_STATE "gold"
#define	_PATH_LASTDEAD	_PATH_PHANTASIA_STATE "lastdead"
#define	_PATH_MESS	_PATH_PHANTASIA_STATE "mess"
#define	_PATH_MONST	_PATH_PHANTASIA_STATE "monsters"
#define	_PATH_MOTD	_PATH_PHANTASIA_STATE "motd"
#define	_PATH_PEOPLE	_PATH_PHANTASIA_STATE "characs"
#define	_PATH_SCORE	_PATH_PHANTASIA_STATE "scoreboard"
#define	_PATH_VOID	_PATH_PHANTASIA_STATE "void"
