#include "../config.h"
#define	_PATH_GOLD	_PATH_GAME_STATE "phantasia/gold"
#define	_PATH_LASTDEAD	_PATH_GAME_STATE "phantasia/lastdead"
#define	_PATH_MESS	_PATH_GAME_STATE "phantasia/mess"
#define	_PATH_MONST	_PATH_GAME_STATE "phantasia/monsters"
#define	_PATH_MOTD	_PATH_GAME_STATE "phantasia/motd"
#define	_PATH_PEOPLE	_PATH_GAME_STATE "phantasia/characs"
#define	_PATH_SCORE	_PATH_GAME_STATE "phantasia/scoreboard"
#define	_PATH_VOID	_PATH_GAME_STATE "phantasia/void"
