.\" This file is free software, distributed under the BSD license.
.Dd May 31, 1993
.Dt ARITHMETIC 6
.Os
.Sh NAME
.Nm arithmetic
.Nd quiz on simple arithmetic
.Sh SYNOPSIS
.Nm
.Op Fl o Ar +\-x/
.Op Fl r Ar range
.Sh DESCRIPTION
.Nm
asks you to solve problems in simple arithmetic. Each question must be
answered correctly before going on to the next. After every 20 problems,
it prints the score so far and the time taken. You can quit at any time
by entering 'q'.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl o
By default,
.Nm
asks questions on addition of numbers from 0 to 10, and corresponding
subtraction. By supplying one or more of the characters
.Ar +\-x/ ,
you can ask for problems in addition, subtraction, multiplication, and
division, respectively. If you give one of these characters more than
once, that kind of problem will be asked correspondingly more often.
.It Fl r
If a
.Ar range
is supplied,
.Nm
selects the numbers in its problems in the following way. For addition
and multiplication, the numbers to be added or multiplied are from 1 to
.Ar range.
For subtraction and division, both the required result and the number
to divide by or subtract will be from 1 to
.Ar range.
The default
.I range
is 10.
.El
