.\" This file is free software, distributed under the BSD license.
.Dd May 31, 1993
.Dt FISH 6
.Os
.Sh NAME
.Nm gofish
.Nd play
.Dq Go Fish
.Sh DESCRIPTION
.Nm
is the game
.Dq Go Fish ,
a traditional children's card game.
.Pp
The computer deals the player and itself seven cards, and places
the rest of the deck face-down (figuratively).
The object of the game is to collect
.Dq books ,
or all of the members of a single rank.
For example, collecting four 2's would give the player a
.Dq book of 2's .
.Pp
The computer makes a random decision as to who gets to start the game,
and then the computer and player take turns asking each other for cards
of a specified rank. If the asked player has any cards of the requested
rank, they give them up to the asking player. A player must have at least
one of the cards of the rank they request in his hand. When a player asks
for a rank of which the other player has no cards, the asker is told to
.Dq Go Fish! .
Then, the asker draws a card from the non-dealt cards. If he draws the
card he asked for, he continue his turn, asking for more ranks from the
other player. Otherwise, the other player gets a turn.
.Pp
When a player completes a book, either by getting cards from the other
player or drawing from the deck, they set those cards aside and the rank
is no longer in play.
.Pp
The game ends when either player no longer has any cards in their hand.
The player with the most books wins.
.Pp
.Nm
provides instructions as to what input it accepts.
