#pragma once
enum {
    STRANGE_OBJECT,
    AMULET_OF_YENDOR,
    FOOD_RATION,
    TRIPE_RATION,
    PANCAKE,
    DEAD_LIZARD,
    FORTUNE_COOKIE,
    CARROT,
    TIN,
    ORANGE,
    APPLE, // 10
    PEAR,
    MELON,
    BANANA,
    CANDY_BAR,
    EGG,
    CLOVE_OF_GARLIC,
    LUMP_OF_ROYAL_JELLY,
    DEAD_HUMAN,
    DEAD_GIANT_ANT,
    DEAD_GIANT_BAT, // 20
    DEAD_CENTAUR,
    DEAD_DRAGON,
    DEAD_FLOATING_EYE,
    DEAD_FREEZING_SPHERE,
    DEAD_GNOME,
    DEAD_HOBGOBLIN,
    DEAD_STALKER,
    DEAD_JACKAL,
    DEAD_KOBOLD,
    DEAD_LEPRECHAUN, // 30
    DEAD_NYMPH,
    DEAD_ORC,
    DEAD_PURPLE_WORM,
    DEAD_QUASIT,
    DEAD_RUST_MONSTER,
    DEAD_SNAKE,
    DEAD_TROLL,
    DEAD_UMBER_HULK,
    DEAD_VAMPIRE,
    DEAD_WRAITH, // 40
    DEAD_XORN,
    DEAD_YETI,
    DEAD_ZOMBIE,
    DEAD_ACID_BLOB,
    DEAD_GIANT_BEETLE,
    DEAD_COCKATRICE,
    DEAD_DOG,
    DEAD_ETTIN,
    DEAD_FOG_CLOUD,
    DEAD_GELATINOUS_CUBE, // 50
    DEAD_HOMUNCULUS,
    DEAD_IMP,
    DEAD_JAGUAR,
    DEAD_KILLER_BEE,
    DEAD_LEOCROTTA,
    DEAD_MINOTAUR,
    DEAD_NURSE,
    DEAD_OWLBEAR,
    DEAD_PIERCER,
    DEAD_QUIVERING_BLOB, // 60
    DEAD_GIANT_RAT,
    DEAD_GIANT_SCORPION,
    DEAD_TENGU,
    DEAD_UNICORN,
    DEAD_VIOLET_FUNGI,
    DEAD_XAN,
    DEAD_YELLOW_LIGHT,
    DEAD_ZRUTY,
    ARROW,
    SLING_BULLET, // 70
    CROSSBOW_BOLT,
    DART,
    ROCK,
    BOOMERANG,
    MACE,
    AXE,
    FLAIL,
    LONG_SWORD,
    TWO_HANDED_SWORD,
    DAGGER, // 80
    SPEAR,
    BOW,
    SLING,
    CROSSBOW,
    CAN_OPENER,
    PICK_AXE,
    EXPENSIVE_CAMERA,
    ICE_BOX,
    ENORMOUS_ROCK,
    HELMET, // 90
    PLATE_MAIL,
    SPLINT_MAIL,
    BANDED_MAIL,
    CHAIN_MAIL,
    SCALE_MAIL,
    RING_MAIL,
    STUDDED_LEATHER_ARMOR,
    LEATHER_ARMOR,
    ELVEN_CLOAK,
    SHIELD, // 100
    PAIR_OF_GLOVES,
    POT_RESTORE_STRENGTH,
    POT_BOOZE,
    POT_INVISIBILITY,
    POT_FRUIT_JUICE,
    POT_HEALING,
    POT_PARALYSIS,
    POT_MONSTER_DETECTION,
    POT_OBJECT_DETECTION,
    POT_SICKNESS, // 110
    POT_CONFUSION,
    POT_GAIN_STRENGTH,
    POT_SPEED,
    POT_BLINDNESS,
    POT_GAIN_LEVEL,
    POT_EXTRA_HEALING,
    POT_LEVITATION,
    SCR_ENCHANT_ARMOR,
    SCR_DESTROY_ARMOR,
    SCR_CONFUSE_MONSTER, // 120
    SCR_SCARE_MONSTER,
    SCR_BLANK_PAPER,
    SCR_REMOVE_CURSE,
    SCR_ENCHANT_WEAPON,
    SCR_DAMAGE_WEAPON,
    SCR_CREATE_MONSTER,
    SCR_GENOCIDE,
    SCR_LIGHT,
    SCR_TELEPORTATION,
    SCR_GOLD_DETECTION, // 130
    SCR_FOOD_DETECTION,
    SCR_IDENTIFY,
    SCR_MAGIC_MAPPING,
    SCR_AMNESIA,
    SCR_FIRE,
    WAN_LIGHT,
    WAN_SECRET_DOOR_DETECTION,
    WAN_CREATE_MONSTER,
    WAN_WISHING,
    WAN_STRIKING, // 140
    WAN_SLOW_MONSTER,
    WAN_SPEED_MONSTER,
    WAN_UNDEAD_TURNING,
    WAN_POLYMORPH,
    WAN_CANCELLATION,
    WAN_TELEPORTATION,
    WAN_MAKE_INVISIBLE,
    WAN_DIGGING,
    WAN_MAGIC_MISSILE,
    WAN_FIRE, // 150
    WAN_SLEEP,
    WAN_COLD,
    WAN_DEATH,
#define Adornment		_u.uprops[1].p_flgs
    RIN_ADORNMENT,
#define Teleportation		_u.uprops[2].p_flgs
    RIN_TELEPORTATION,
#define Regeneration		_u.uprops[3].p_flgs
    RIN_REGENERATION,
#define Searching		_u.uprops[4].p_flgs
    RIN_SEARCHING,
#define See_invisible		_u.uprops[5].p_flgs
    RIN_SEE_INVISIBLE,
#define Stealth		_u.uprops[6].p_flgs
    RIN_STEALTH,
#define Levitation		_u.uprops[7].p_flgs
    RIN_LEVITATION, // 160
#define Poison_resistance		_u.uprops[8].p_flgs
    RIN_POISON_RESISTANCE,
#define Aggravate_monster		_u.uprops[9].p_flgs
    RIN_AGGRAVATE_MONSTER,
#define Hunger		_u.uprops[10].p_flgs
    RIN_HUNGER,
#define Fire_resistance		_u.uprops[11].p_flgs
    RIN_FIRE_RESISTANCE,
#define Cold_resistance		_u.uprops[12].p_flgs
    RIN_COLD_RESISTANCE,
#define Protection_from_shape_changers		_u.uprops[13].p_flgs
    RIN_PROTECTION_FROM_SHAPE_CHANGERS,
#define Conflict		_u.uprops[14].p_flgs
    RIN_CONFLICT,
#define Gain_strength		_u.uprops[15].p_flgs
    RIN_GAIN_STRENGTH,
#define Increase_damage		_u.uprops[16].p_flgs
    RIN_INCREASE_DAMAGE,
#define Protection		_u.uprops[17].p_flgs
    RIN_PROTECTION, // 170
#define Warning		_u.uprops[18].p_flgs
    RIN_WARNING,
#define Teleport_control		_u.uprops[19].p_flgs
    RIN_TELEPORT_CONTROL,
    DIAMOND,
    RUBY,
    SAPPHIRE,
    EMERALD,
    TURQUOISE,
    AQUAMARINE,
    TOURMALINE,
    TOPAZ, // 180
    OPAL,
    GARNET,
    AMETHYST,
    AGATE,
    ONYX,
    JASPER,
    JADE,
    BLUE_GLASS,
    RED_GLASS,
    YELLOW_GLASS, // 190
    GREEN_GLASS,
    NROFOBJECTS,

    CORPSE	= DEAD_HUMAN,
    LAST_GEM	= (JADE+1),
    LAST_RING	= 19,
};
