// Copyright (c) 1985, Stichting Centrum voor Wiskunde en Informatica,
// Copyright (c) 1982 Jay Fenlason <hack@gnu.org>
// This file is free software, distributed under the BSD license.

#include "hack.h"
#include "extern.h"

//{{{ Rumors -----------------------------------------------------------

enum { N_RUMORS = 442 };	// Set to number of lines in c_Rumors

static const char c_Rumors[] =
"\"Quit\" is a four letter word.\0"
"\"So when I die, the first thing I will see in Heaven is a score list?\"\0"
"...and rings may protect your fingers.\0"
"...and sometimes a piercer drops by.\0"
"A Quasit is even faster than a jaguar!\0"
"A clove of garlic a day keeps your best friends away.\0"
"A cockatrice's corpse is guaranteed to be untainted!\0"
"A confused acid blob may attack.\0"
"A dead lizard is a good thing to turn undead.\0"
"A dragon is just a Snake that ate a scroll of fire.\0"
"A fading corridor enlightens your insight.\0"
"A glowing potion is too hot to drink.\0"
"A good amulet may protect you against guards.\0"
"A homunculus wouldnt want to hurt a wizard.\0"
"A jaguar shouldn't frighten you.\0"
"A magic vomit pump is a necessity for gourmands.\0"
"A monstrous mind is a toy for ever.\0"
"A nurse a day keeps the doctor away.\0"
"A potion of blindness makes you see invisible things.\0"
"A ring is just a wound wand.\0"
"A ring of adornment protects against Nymphs.\0"
"A ring of conflict is a bad thing if there is a nurse in the room.\0"
"A ring of extra ringfinger is useless if not enchanted.\0"
"A ring of stealth can be recognised by that it does not teleport you.\0"
"A rope may form a trail in a maze.\0"
"A rumour has it that rumours are just rumours.\0"
"A scroll of enchant amulet is only useful on your way back.\0"
"A smoky potion surely affects your vision.\0"
"A spear might hit a nurse.\0"
"A spear will hit an ettin.\0"
"A staff may recharge if you drop it for awhile.\0"
"A tin of smoked eel is a wonderful find.\0"
"A truly wise man never plays leapfrog with a unicorn.\0"
"A two-handed sword usually misses.\0"
"A visit to the Zoo is very educational; you meet interesting animals.\0"
"A wand of deaf is a more dangerous weapon than a wand of sheep.\0"
"A wand of vibration might bring the whole cave crashing about your ears.\0"
"A winner never quits. A quitter never wins.\0"
"A xan is a small animal. It doesn't reach higher than your leg.\0"
"Acid blobs should be attacked bare-handed.\0"
"Affairs with Nymphs are often very expensive.\0"
"Afraid of falling piercers? Wear a helmet!\0"
"After being attacked by a Harpy you have a lot of arrows.\0"
"All monsters are created evil, but some are more evil than others.\0"
"Always attack a floating Eye from behind!\0"
"Always be aware of the phase of the moon!\0"
"Always read the info about a monster before dealing with it.\0"
"Always sweep the floor before engraving important messages.\0"
"Amulets are hard to make. Even for a wand of wishing.\0"
"An Umber hulk can be a confusing sight.\0"
"An elven cloak is always the height of fashion.\0"
"An elven cloak protects against magic.\0"
"An ettin is hard to kill; an imp is hard to hit. See the difference?\0"
"Any small object that is accidentally dropped will hide under a larger object.\0"
"Are you blind? Catch a floating Eye!\0"
"Asking about monsters may be very useful.\0"
"Attacking an eel when there is none usually is a fatal mistake!\0"
"Balrogs only appear on the deeper levels.\0"
"Be careful when eating bananas. Monsters might slip on the peels.\0"
"Be careful when eating salmon - your fingers might become greasy.\0"
"Be careful when the moon is in its last quarter.\0"
"Be careful when throwing a boomerang - you might hit the back of your head.\0"
"Be nice to a nurse: put away your weapon and take off your clothes.\0"
"Being digested is a painfully slow process.\0"
"Better go home and hit your kids. They are just little monsters!\0"
"Better go home and play with your kids. They are just little monsters!\0"
"Better leave the dungeon, otherwise you might get hurt badly.\0"
"Beware of dark rooms - they may be the Morgue.\0"
"Beware of death rays!\0"
"Beware of falling rocks, wear a helmet!\0"
"Beware of the minotaur. He's very horny!\0"
"Beware of the potion of Nitroglycerine - it's not for the weak of heart.\0"
"Beware of wands of instant disaster.\0"
"Beware: there's always a chance that your wand explodes as you try to zap it!\0"
"Beyond the 23-rd level lies a happy retirement in a room of your own.\0"
"Blank scrolls make more interesting reading.\0"
"Blind? Eat a carrot!\0"
"Booksellers never read scrolls; it might carry them too far away.\0"
"Booksellers never read scrolls; it might leave their shop unguarded.\0"
"Changing your suit without dropping your sword? You must be kidding!\0"
"Cockatrices might turn themselves to stone faced with a mirror.\0"
"Consumption of home-made food is strictly forbidden in this dungeon.\0"
"Dark gems are just coloured glass.\0"
"Dark room? Just flash often with your camera.\0"
"Dark room? Your chance to develop your photographs!\0"
"Dark rooms are not *completely* dark: just wait and let your eyes adjust...\0"
"Dead lizards protect against a cockatrice.\0"
"Death is just around the next door.\0"
"Death is life's way of telling you you've been fired.\0"
"Descend in order to meet more decent monsters.\0"
"Didn't you forget to pay?\0"
"Didn't you forget to pay?\0"
"Direct a direct hit on your direct opponent, directing in the right direction.\0"
"Do something big today: lift a boulder.\0"
"Do you want to visit hell? Dig a *very* deep hole.\0"
"Don't bother about money: only Leprechauns and shopkeepers are interested.\0"
"Don't create fireballs: they might turn against you.\0"
"Don't eat too much: you might start hiccoughing!\0"
"Don't play hack at your work, your boss might hit you!\0"
"Don't swim with weapons or armour: they might rust!\0"
"Don't tell a soul you found a secret door, otherwise it isn't secret anymore.\0"
"Don't throw gems. They are so precious! Besides, you might hit a roommate.\0"
"Drinking might affect your health.\0"
"Drop your vanity and get rid of your jewels! Pickpockets about!\0"
"Dungeon expects every monster to do his duty.\0"
"Dust is an armor of poor quality.\0"
"Eat 10 cloves of garlic and keep all humans at a two-square distance.\0"
"Eat a homunculus if you want to avoid sickness.\0"
"Eating a Wraith is a rewarding experience!\0"
"Eating a freezing sphere is like eating a yeti.\0"
"Eating a killer bee is like eating a scorpion.\0"
"Eating a tengu is like eating a Nymph.\0"
"Eating unpaid Leprechauns may be advantageous.\0"
"Eels hide under mud. Use a unicorn to clear the water and make them visible.\0"
"Elven cloaks cannot rust.\0"
"Engrave your wishes with a wand of wishing.\0"
"Eventually all wands of striking do strike.\0"
"Eventually you will come to admire the swift elegance of a retreating nymph.\0"
"Ever fought with an enchanted tooth?\0"
"Ever heard hissing outside? I *knew* you hadn't!\0"
"Ever seen a leocrotta dancing the tengu?\0"
"Ever slept in the arms of a homunculus?\0"
"Ever tried digging through a Vault Guard?\0"
"Ever tried enchanting a rope?\0"
"Ever tried to catch a flying boomerang?\0"
"Ever tried to put a Troll into a large box?\0"
"Ever wondered why one would want to dip something in a potion?\0"
"Every hand has only one finger to put a ring on. You've got only two hands. So?\0"
"Every level contains a shop; only the entrance is often hidden.\0"
"Everybody should have tasted a scorpion at least once in his life.\0"
"Expensive cameras have penetrating flashlights.\0"
"Feeding the animals is strictly prohibited. The Management.\0"
"Feeling lousy? Why don't you drink a potion of tea?\0"
"Fiery letters might deter monsters.\0"
"First Law of Hacking: leaving is much more difficult than entering.\0"
"For any remedy there is a misery.\0"
"Fourth Law of Hacking: you will find the exit at the entrance.\0"
"Gems are the droppings of other inmates.\0"
"Gems do get a burden.\0"
"Getting Hungry? Stop wearing rings!\0"
"Getting Hungry? Wear an amulet!\0"
"Ghosts always empty the fridge.\0"
"Ghosts are visible because they don't leave a trace.\0"
"Giant beetles make giant holes in giant trees!\0"
"Gold is a heavy metal.\0"
"Good day for overcoming obstacles. Try a steeplechase.\0"
"Gossip is the opiate of the depressed.\0"
"Hackers do it with bugs.\0"
"Half Moon tonight. (At least it's better than no Moon at all.)\0"
"Handle your flasks carefully - there might be a ghost inside!\0"
"Have a good meal today: eat a minotaur.\0"
"Hey guys, you *WIELD* a dead lizard against a cocatrice! [David London]\0"
"Hissing is a sound I hate.\0"
"Hitting is the lingua franca in these regions.\0"
"Humans use walking canes when they grow old.\0"
"Hungry? There is an abundance of food on the next level.\0"
"Hungry? Wear an amulet!\0"
"I doubt whether nurses are virgins.\0"
"I guess you have never hit a postman with an Amulet of Yendor yet...\0"
"I once knew a hacker who ate too fast and choked to death.....\0"
"I smell a maze of twisty little passages.\0"
"I wished, I never wished a wand of wishing. (Wishful thinking)\0"
"If \"nothing happens\", something *has* happened anyway!!\0"
"If a shopkeeper kicks you out of his shop, he'll kick you out of the dungeon.\0"
"If you are the shopkeeper you can take things for free.\0"
"If you are too cute some monsters might be tempted to embrace you.\0"
"If you can't learn to do it well, learn to enjoy doing it badly.\0"
"If you need a wand of digging, kindly ask the minotaur.\0"
"If you see nurses you better start looking somewhere for a doctor.\0"
"If you want to feel great, you must eat something real big.\0"
"If you want to float you'd better eat a floating eye.\0"
"If you want to genocide nurses, genocide @'s.\0"
"If you want to hit, use a dagger.\0"
"If you're afraid of trapdoors, just cover the floor with all you've got.\0"
"If you're lost, try buying a map next time you're in a shop.\0"
"If your ghost kills a player, it increases your score.\0"
"Important mail? Be careful that it isn't stolen!\0"
"Improve your environment, using a wand of rearrangement.\0"
"In a hurry? Try a ride on a fast moving quasit!\0"
"In a way, a scorpion is like a snake.\0"
"In need of a rest? Quaff a potion of sickness!\0"
"In total, there are eight sorts of shops.\0"
"Inside a shop you better take a look at the price tags before buying anything.\0"
"It furthers one to see the great man.\0"
"It is bad manners to use a wand in a shop.\0"
"It is said that purple worms and trappers fill the same niche.\0"
"It might be a good idea to offer the unicorn a ruby.\0"
"It seems you keep overlooking a sign reading \"No trespassing\"!\0"
"It's all a matter of life and death, so beware of the undead.\0"
"It's bad luck to drown a postman.\0"
"It's easy to overlook a monster in a wood.\0"
"It's not safe to Save.\0"
"Jackals are intrinsically rotten.\0"
"Just below any trapdoor there may be another one. Just keep falling!\0"
"Keep a clear mind: quaff clear potions.\0"
"Keep your armours away from rust.\0"
"Keep your weaponry away from acids.\0"
"Kicking the terminal doesn't hurt the monsters.\0"
"Kill a unicorn and you kill your luck.\0"
"Killer bees keep appearing till you kill their queen.\0"
"Latest news? Put 'net.games.hack' in your .newsrc !\0"
"Latest news? Put newsgroup 'netUNX.indoor.hackers-scroll' in your .newsrc!\0"
"Learn how to spell. Play Hack!\0"
"Leather armour cannot rust.\0"
"Leprechauns are the most skilled cutpurses in this dungeon.\0"
"Leprechauns hide their gold in a secret room.\0"
"Let your fingers do the walking on the yulkjhnb keys.\0"
"Let's face it: this time you're not going to win.\0"
"Let's have a party, drink a lot of booze.\0"
"Liquor sellers do not drink; they hate to see you twice.\0"
"Looking for a monster -- use a staff of monster summoning.\0"
"Looking pale? Quaff a red potion!\0"
"M.M.Vault cashiers teleport any amount of gold to the next local branch.\0"
"Many monsters make a murdering mob.\0"
"Meeting your own ghost decreases your luck considerably!\0"
"Memory flaw - core dumped.\0"
"Money is the root of all evil.\0"
"Money to invest? Take it to the local branch of the Magic Memory Vault!\0"
"Monsters come from nowhere to hit you everywhere.\0"
"Monsters sleep because you are boring, not because they ever get tired.\0"
"Most monsters can't swim.\0"
"Most monsters prefer minced meat. That's why they are hitting you!\0"
"Most rumors are just as misleading as this one.\0"
"Much ado Nothing Happens.\0"
"Murder complaint? Mail to 'netnix!devil!gamble!freak!trap!lastwill!rip'.\0"
"Need money? Sell your corpses to a tin factory.\0"
"Never ask a shopkeeper for a price list.\0"
"Never attack a guard.\0"
"Never eat with glowing hands!\0"
"Never fight a monster: you might get killed.\0"
"Never go into the dungeon at midnight.\0"
"Never kiss an animal. It may cause kissing disease.\0"
"Never map the labyrinth.\0"
"Never mind the monsters hitting you: they just replace the charwomen.\0"
"Never step on a cursed engraving.\0"
"Never swim with a camera: there's nothing to take pictures of.\0"
"Never trust a random generator in magic fields.\0"
"Never use a wand of death.\0"
"Never use your best weapon to engrave a curse.\0"
"Never vomit on a door mat.\0"
"No easy fighting with a heavy load!\0"
"No level contains two shops. The maze is no level. So...\0"
"No part of this fortune may be reproduced, stored in a retrieval system, ...\0"
"Not all rumors are as misleading as this one.\0"
"Not even a spear will hit a Xorn.\0"
"Now what is it that cures digestion?\0"
"Nurses are accustomed to touch naked persons: they don't harm them.\0"
"Nurses prefer undressed hackers.\0"
"Nymphs and nurses like beautiful rings.\0"
"Nymphs are blondes. Are you a gentleman?\0"
"Nymphs are very pleased when you call them by their real name: Lorelei.\0"
"Offering a unicorn a worthless piece of glass might prove to be fatal!\0"
"Old hackers never die: young ones do.\0"
"Old trees sometimes fall without a warning!\0"
"One can even choke in a fortune cookie!\0"
"One has to leave shops before closing time.\0"
"One homunculus a day keeps the doctor away.\0"
"One level further down somebody is getting killed, right now.\0"
"One wand of concentration equals eight scrolls of create monster.\0"
"Only Today! A dramatic price-cut on slightly used wands.\0"
"Only a dragon will never get a cold from a wand of cold.\0"
"Only a real dummy would ever call his sword 'Elbereth'.\0"
"Only a wizard can use a magic whistle.\0"
"Only cave-women can catch a unicorn. And then only with a golden rope.\0"
"Only chaotic evils kill sleeping monsters.\0"
"Only david can find the zoo!\0"
"Only real trappers escape traps.\0"
"Only real wizards can write scrolls.\0"
"Only wizards are able to zap a wand.\0"
"Opening a tin is difficult, especially when you are not so strong!\0"
"Opening a tin is difficult, especially when you attempt this bare handed!\0"
"Operation coded OVERKILL has started now.\0"
"Orcs and killer bees share their lifestyle.\0"
"Orcs do not procreate in dark rooms.\0"
"PLEASE ignore previous rumour.\0"
"Plain nymphs are harmless.\0"
"Playing billiards pays when you are in a shop.\0"
"Praying will frighten Demons.\0"
"Pursue the monsters and you will be had indeed.\0"
"Put on a ring of teleportation: it will take you away from onslaught.\0"
"Rays aren't boomerangs, of course, but still...\0"
"Read the manual before entering the cave - You might get killed otherwise.\0"
"Reading Herbert will disgust you, but in one case it might be enlightening.\0"
"Reading Tolkien might help you.\0"
"Reading might change your vision.\0"
"Reading might improve your scope.\0"
"Ropes are made from the long, blond hairs of dead Nymphs.\0"
"Row (3x) that boat gently down the stream, Charon (4x), death is but a dream.\0"
"Running is good for your legs.\0"
"Rust monsters love water. There are potions they hate, however.\0"
"Savings do include amnesia.\0"
"Scorpions often hide under tripe rations.\0"
"Screw up your courage!  You've screwed up everything else.\0"
"Scrolls of fire are useful against fog clouds.\0"
"Second Law of Hacking: first in, first out.\0"
"Selling and rebuying a wand will recharge it.\0"
"Shopkeepers accept creditcards, as long as you pay cash.\0"
"Shopkeepers are vegetarians: they only eat Swedes.\0"
"Shopkeepers can't read, so what use is engraving in a shop?\0"
"Shopkeepers can't swim.\0"
"Shopkeepers have incredible patience.\0"
"Shopkeepers often have strange names.\0"
"Shopkeepers sometimes die from old age.\0"
"Sleeping may increase your strength.\0"
"Snakes are often found under worthless objects.\0"
"Some Balrogs don't attack if you offer them a ring.\0"
"Some mazes (especially small ones) have no solutions, says man 6 maze.\0"
"Some potions are quite mind-expanding.\0"
"Some questions Sphynxes ask just *don't* have any answers.\0"
"Sometimes \"mu\" is the answer.\0"
"Sometimes monsters are more likely to fight each other than attack you.\0"
"Sorry, no fortune this time. Better luck next cookie!\0"
"Spare your scrolls of make-edible until it's really necessary!\0"
"Speed Kills (The Doors)\0"
"Spinach, carrot, and a melon - a meal fit for a nurse!\0"
"Stay clear of the level of no return.\0"
"Suddenly the dungeon will collapse ...\0"
"Tainted meat is even more sickening than poison!\0"
"Taming a postman may cause a system security violation.\0"
"Taming is a gradual process of excercising and rewarding.\0"
"Telepathy is just a trick: once you know how to do it, it's easy.\0"
"Teleportation lessens your orientation.\0"
"The \"pray\" command is not yet implemented.\0"
"The Jackal only eats bad food.\0"
"The Leprechaun Gold Tru$t is no division of the Magic Memory Vault.\0"
"The Leprechauns hide their treasure in a small hidden room.\0"
"The air is positively magic in here. Better wear a negative armor.\0"
"The best equipment for your work is, of course, the most expensive.\0"
"The emptiness of a ghost is too heavy to bear.\0"
"The key to this game is that there are no keys.\0"
"The longer the wand the better.\0"
"The moon is not the only heavenly body to influence this game.\0"
"The postman always rings twice.\0"
"The proof of the quivering blob is in the eating thereof.\0"
"The secret of wands of Nothing Happens: try again!\0"
"The use of dynamite is dangerous.\0"
"There are better information sources than fortune cookies.\0"
"There are monsters of softening penetration.\0"
"There are monsters of striking charity.\0"
"There have been people like you in here; their ghosts seek revenge on you.\0"
"There is a VIP-lounge on this level. Only first-class travellers admitted.\0"
"There is a big treasure hidden in the zoo!\0"
"There is a message concealed in each fortune cookie.\0"
"There is a trap on this level!\0"
"There is more magic in this cave than meets the eye.\0"
"There is no business like throw business.\0"
"There seem to be monsters of touching benevolence.\0"
"They say a gelatinous cube can paralyse you...\0"
"They say that Elven cloaks absorb enchantments.\0"
"They say that a dagger hits.\0"
"They say that a spear will hit a Dragon.\0"
"They say that a spear will hit a Xorn.\0"
"They say that a spear will hit a neo-otyugh. (Do YOU know what that is?)\0"
"They say that a spear will hit an ettin.\0"
"They say that a two-handed sword misses.\0"
"They say that a unicorn might bring you luck.\0"
"They say that an elven cloak may be worn over your armor.\0"
"They say that an elven cloak protects against magic.\0"
"They say that cavemen seldom find tins in the dungeon.\0"
"They say that dead lizards protect against a cockatrice.\0"
"They say that killing a shopkeeper brings bad luck.\0"
"They say that monsters never step on a scare monster scroll.\0"
"They say that only david can find the zoo!\0"
"They say that shopkeepers often have a large amount of money in their purse.\0"
"They say that the owner of the dungeon might change it slightly.\0"
"They say that the use of dynamite is dangerous.\0"
"They say that the walls in shops are made of extra hard material.\0"
"They say that there is a big treasure hidden in the zoo!\0"
"They say that there is a message concealed in each fortune cookie.\0"
"They say that there is a trap on this level!\0"
"They say that you can meet old friends in the caves.\0"
"They say that you can't take your pick-axe into a shop.\0"
"They say that you cannot trust scrolls of rumour.\0"
"They say that you need a key in order to open locked doors.\0"
"Third Law of Hacking: the last blow counts most.\0"
"This dungeon is restroom equipped (for your convenience).\0"
"This fortune cookie is property of Fortune Cookies, Inc.\0"
"This is not a fortune.\0"
"This is the Leprechaun Law: every purse has a price.\0"
"Tin openers are rare indeed.\0"
"Tired of irritating bats? Try a scroll of silence.\0"
"To hit or not to hit, that is the question.\0"
"To reach heaven, escape the dungeon while wearing a ring of levitation.\0"
"Tranquillizers might get you killed.\0"
"Travel fast, use some magic speed!\0"
"Tripe on its own is revolting,  but with onions it's delicious!\0"
"Try hacking in the wee hours: you will have more room.\0"
"Try the fall back end run play against ghosts.\0"
"Ulch, that meat was painted.\0"
"Unwanted mail? Sell it to the bookshop!\0"
"Vampires hate garlic.\0"
"Vault guards always make sure you aren't a shopkeeper.\0"
"Vault guards never disturb their Lords.\0"
"Visitors are requested not to apply genocide to shopkeepers.\0"
"WARNING from H.M. Govt:  Quaffing may be dangerous to your health.\0"
"Wanna fly? Eat a bat.\0"
"Want a hint? Zap a wand of make invisible on your weapon!\0"
"Want fun? Throw a potion in a pool and go swimming!\0"
"Want to conserve your dead corpses? Go to the tin factory!\0"
"Wanted: shopkeepers. Send a scroll of mail to: Mage of Yendor/Level 35/Dungeon.\0"
"Warning: end of file 'fortunes' reached.\0"
"Warning: people who eat dragons can go to hell!!\0"
"Watch your steps on staircases.\0"
"Wear armor, going naked seems to offend public decency in here.\0"
"What a pity, you cannot read it!\0"
"What do you think is the use of dead lizards?\0"
"When a piercer drops in on you, you will be tempted to hit the ceiling!\0"
"When in a maze follow the right wall and you will never get lost.\0"
"When in a shop, do as shopkeepers do.\0"
"When you have a key, you don't have to wait for the guard.\0"
"When you have seen one killer bee, you have seen them all.\0"
"Where do you think all those demons come from? From Hell, of course.\0"
"Where do you think the hell is located? It must be deep, deep down.\0"
"Who should ever have thought one could live from eating fog clouds?\0"
"Why a \"2\" for the postman? Well, how many times does he ring?\0"
"Why should one ever throw an egg to a cockatrice?\0"
"Why would anybody in his sane mind engrave \"Elbereth\"?\0"
"Wish for a master key and open the Magic Memory Vault!\0"
"Wish for a pass-key and pass all obstacles!\0"
"Wish for a skeleton-key and open all doors!\0"
"Wishing too much may bring you too little.\0"
"Wizards do not sleep.\0"
"You are heading for head-stone for sure.\0"
"You are just the kind of bad food some monsters like to digest.\0"
"You can always wear an elven cloak.\0"
"You can get a genuine Amulet of Yendor by doing the following:  -- more --\0"
"You can't get rid of a cursed plate mail with a can-opener.\0"
"You can't leave a shop through the back door: there ain't one!\0"
"You cannot trust scrolls of rumour.\0"
"You die...\0"
"You feel greedy and want more gold? Why don't you try digging?\0"
"You feel like someone is pulling your leg.\0"
"You have to outwit a Sphynx or pay her.\0"
"You may get rich selling letters, but beware of being blackmailed!\0"
"You might choke on your food by eating fortune cookies.\0"
"You might cut yourself on a long sword.\0"
"You might trick a shopkeeper if you're invisible.\0"
"You need a key in order to open locked doors.\0"
"You want to regain strength? Two levels ahead is a guesthouse!\0"
"You'll need a spear if you want to attack a Dragon.\0"
"You've got to know how to put out a yellow light.\0"
"Zapping a wand of Nothing Happens doesn't harm you a bit.\0"
;
//}}}-------------------------------------------------------------------

static uint8_t _used_rumors [(N_RUMORS+7)/8] = {};

static bool is_rumor_used (unsigned ir)
    { return (_used_rumors[ir/8] >> (ir%8)) & 1; }
static inline void set_rumor_used (unsigned ir)
    { _used_rumors[ir/8] |= (1<<(ir%8)); }
static inline void reset_used_rumors (void)
    { memset (_used_rumors, 0, sizeof(_used_rumors)); }

static const char* get_unused_rumor_after (unsigned ir)
{
    unsigned u = ir;
    while (u < N_RUMORS && is_rumor_used(u))
	++u;
    if (u >= N_RUMORS) {
	u = 0;
	while (u < ir && is_rumor_used(u))
	    ++u;
	if (u >= ir)
	    reset_used_rumors();
    }
    set_rumor_used (u);
    return zstrn (c_Rumors, u, N_RUMORS);
}

void print_rumor (void)
{
    pline ("This cookie has a scrap of paper inside! It reads: ");
    pline (get_unused_rumor_after (nrand(N_RUMORS)));
}
