.\" This file is free software, distributed under the BSD license.
.Dd August 4, 1994
.Dt GOMOKU 6
.Os
.Sh NAME
.Nm gomoku
.Nd game of 5 in a row
.Sh DESCRIPTION
.Nm
is a two player game were the object is to get 5 in a row horizontally,
vertically or diagonally on a 19 by 19 grid. By convention, X always
moves first. The game will display a playing board, make the first move if
randomly chosen to do so, and prompt for moves from the user. Moves are
entered using the cursor, moving with arrow keys or hjkl, and selecting
using space. Press 'q' or F10 to end the game.
.El
.Sh AUTHOR
.An Ralph Campbell
.Sh ACKNOWLEDGEMENTS
The board display routines were based on the
.Nm goref
program written by Peter Langston.
