.\" This file is free software, distributed under the BSD license.
.Dd December 30, 1993
.Dt SPIRHUNT 6
.Os
.Sh NAME
.Nm spirhunt
.Nd space combat game
.Sh SYNOPSIS
.Nm
.Oo
.Op Fl a
.Ar file
.Oc
.Sh DESCRIPTION
.Nm
is a game of space glory and war.
Below is a summary of commands.
For complete documentation, see
.Em Space Pirate Hunt
by Eric Allman.
.Pp
In general, throughout the game, if you forget what is appropriate
the game will tell you what it expects if you just type in a question mark.
.Sh AUTHOR
.An Eric Allman
.Sh COMMAND SUMMARY
.Bl -item -compact
.It
.Ic ca Ns pture
.It
.Ic cl Ns oak
.Ic u Ns p/ Ns Ic d Ns own
.It
.Ic c Ns omputer request; ...
.It
.Ic da Ns mages
.It
.Ic destruct
.It
.Ic do Ns ck
.It
.Ic help
.It
.Ic i Ns mpulse course distance
.It
.Ic l Ns rscan
.It
.Ic m Ns ove course distance
.It
.Ic p Ns lasers Ic a Ns utomatic
amount
.It
.Ic p Ns lasers Ic m Ns anual
amt1 course1 spread1 ...
.It
.Ic t Ns orpedo course
.Op Ic y Ns es
.No angle/ Ns Ic n Ns o
.It
.Ic ram No course distance
.It
.Ic r Ns est time
.It
.Ic shell
.It
.Ic sh Ns ields
.Ic u Ns p/ Ns Ic d Ns own
.It
.Ic s Ns rscan
.Op Ic y Ns es/ Ic n Ns o
.It
.Ic st Ns atus
.It
.Ic quit y Ns es/ Ns Ic n Ns o
.It
.Ic u Ns ndock
.It
.Ic v Ns isual course
.It
.Ic w Ns arp warp_factor
.El
