.\" This file is free software, distributed under the BSD license.
.Dd December 30, 1993
.Dt SPIRHUNT 6
.Os
.Sh NAME
.Nm spirhunt
.Nd space combat game
.Sh DESCRIPTION
.Nm
is a game of space glory and war. Below is a summary of commands.
To print it while playing, press '?'.
.Sh COMMANDS
.Bl -tag -width "a" -compact
.It m
move (ss or qqss)
.It r
rest
.It p
fire plasers
.It I
move under impulse
.It t
fire torpedoes
.It R
ram something
.It c
cloak on/off
.It C
ask pirate to surrender
.It s
shield up/down
.It H
call starbase for help
.It w
set warp factor
.It D
self-destruct
.It d
dock/undock
.It S
save and quit
.It i
damage report
.It Q
quick quit
.El
